Project.MvcClient/Models/ErrorViewModel.cs
namespace Project.MvcClient.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Project.MvcClient/ViewModels/CryptoCurrencyViewModels/CryptoCurrencyRate.cs
using Newtonsoft.Json;

namespace Project.MvcClient.ViewModels.CryptoCurrencyViewModels;

public class CryptoCurrencyRate
{
    [JsonProperty("status")]
    public Status Status { get; set; }

    [JsonProperty("data")]
    public Dictionary<string, CryptoCurrencyQuote> Data { get; set; }
}

public class Status
{
    [JsonProperty("timestamp")]
    public DateTime Timestamp { get; set; }

    [JsonProperty("error_code")]
    public int ErrorCode { get; set; }

    [JsonProperty("error_message")]
    public string ErrorMessage { get; set; }

    [JsonProperty("elapsed")]
    public int Elapsed { get; set; }

    [JsonProperty("credit_count")]
    public int CreditCount { get; set; }

    [JsonProperty("notice")]
    public string Notice { get; set; }
}

public class CryptoCurrencyQuote
{

    [JsonProperty("quote")]
    public Dictionary<string, Quote> Quote { get; set; }
}

public class Quote
{
    [JsonProperty("price")]
    public decimal Price { get; set; }
}

Project.MvcClient/ViewModels/PeopleViewModels/CreatePersonRequest.cs
namespace Project.MvcClient.ViewModels.PeopleViewModels;

public record CreatePersonRequest(string FirstName, string LastName);

Project.MvcClient/ViewModels/PeopleViewModels/CreatePersonResponse.cs
namespace Project.MvcClient.ViewModels.PeopleViewModels;

public record CreatePersonResponse(Guid Id, string FirstName, string LastName);

Project.MvcClient/ViewModels/PeopleViewModels/PersonItemResponse.cs
namespace Project.MvcClient.ViewModels.PeopleViewModels;

public record PersonItem(Guid Id, string FirstName, string LastName);

Project.MvcClient/ViewModels/PeopleViewModels/UpdatePerson.cs
namespace Project.MvcClient.ViewModels.PeopleViewModels;

public record UpdatePerson(Guid Id, string FirstName, string LastName);

Project.MvcClient/Controllers/CryptoCurrenciesController.cs
using Microsoft.AspNetCore.Mvc;
using Project.MvcClient.Contracts;
using Project.MvcClient.Responses;
using Project.MvcClient.ViewModels.CryptoCurrencyViewModels;

namespace Project.MvcClient.Controllers;

[Route("[controller]/[action]")]
public class CryptoCurrenciesController : Controller
{
    private readonly ILogger<CryptoCurrenciesController> _logger;
    private readonly IGenericHttpService _genericHttpService;


    public CryptoCurrenciesController(
        ILogger<CryptoCurrenciesController> logger,
        IGenericHttpService genericHttpService)
    {
        _logger = logger;
        _genericHttpService = genericHttpService;
    }

    [HttpGet]
    public async Task<ActionResult> Index()
    {
        ResultStatus result = await _genericHttpService.GetAsync<CryptoCurrencyRate>("Api", "api/CryptoCurrencyRate/1");
        if (result.IsSuccess)
        {
            return View((CryptoCurrencyRate)result.Data!);
        }
        throw new Exception(result.Message);
    }
}

Project.MvcClient/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Project.MvcClient.Contracts;
using Project.MvcClient.Responses;
using Project.MvcClient.ViewModels.PeopleViewModels;

namespace Project.MvcClient.Controllers;

public class PeopleController : Controller
{
    private readonly ILogger<PeopleController> _logger;
    private readonly IGenericHttpService _genericHttpService;


    public PeopleController(ILogger<PeopleController> logger,
        IGenericHttpService genericHttpService)
    {
        _logger = logger;
        _genericHttpService = genericHttpService;
    }

    public async Task<ActionResult<List<PersonItem>>> Index()
    {
        ResultStatus result = await _genericHttpService.GetAsync<IList<PersonItem>>("Api", "api/People");
        if (result.IsSuccess)
        {
            return View((List<PersonItem>)result.Data);
        }
        throw new Exception(result.Message);
    }

    [HttpGet("{id}"), ActionName("Details")]
    public async Task<ActionResult<PersonItem>> Details(Guid id)
    {
        ResultStatus result = await _genericHttpService.GetAsync<PersonItem>("Api", $"api/People/{id}");
        if (result.IsSuccess)
        {
            return View((PersonItem)result.Data);
        }
        throw new Exception(result.Message);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult<CreatePersonResponse>> CreateAsync(CreatePersonRequest personRequest)
    {
        HttpContent content = JsonContent.Create(personRequest);

        ResultStatus result = await _genericHttpService.PostAsync<CreatePersonResponse>("Api", "api/People", content);

        if (result.IsSuccess)
        {
            return RedirectToAction(nameof(Index));
        }
        throw new Exception(result.Message);
    }

    [HttpGet, ActionName("Edit")]
    public async Task<IActionResult> UpdateAsync(Guid id)
    {
        ResultStatus result = await _genericHttpService.GetAsync<UpdatePerson>("Api", $"api/People/{id}");

        if (result.IsSuccess)
        {
            return View((UpdatePerson)result.Data);
        }
        throw new Exception(result.Message);
    }

    [HttpPost, ActionName("Edit")]
    public async Task<ActionResult<UpdatePerson>> UpdateAsync(UpdatePerson personRequest)
    {
        HttpContent content = JsonContent.Create(personRequest);

        ResultStatus result = await _genericHttpService.UpdateAsync<UpdatePerson>("Api", $"api/People/{personRequest.Id}", content);

        if (result.IsSuccess)
        {
            return RedirectToAction(nameof(Index));
        }
        throw new Exception(result.Message);
    }

    [HttpGet, ActionName("Delete")]
    public async Task<ActionResult<PersonItem>> DeleteAsync(Guid id)
    {
        ResultStatus result = await _genericHttpService.GetAsync<PersonItem>("Api", $"api/People/{id}");

        if (result.IsSuccess)
        {
            return View((PersonItem)result.Data);
        }
        throw new Exception(result.Message);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<ActionResult<CreatePersonResponse>> PostDeleteAsync(Guid id)
    {
        ResultStatus result = await _genericHttpService.DeleteAsync<Guid>("Api", $"api/People/{id}");

        if (result.IsSuccess)
        {
            return RedirectToAction(nameof(Index));
        }
        throw new Exception(result.Message);
    }
}

Project.MvcClient/Views/CryptoCurrencies/Index.cshtml
@using Project.MvcClient.ViewModels.CryptoCurrencyViewModels
@model CryptoCurrencyRate

@{
    ViewData["Title"] = "Bitcoin Prices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Bitcoin Prices</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Currency</th>
            <th>
                Price
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (KeyValuePair<string, Quote> quote in Model.Data["1"].Quote)
        {
            <tr>
                <th scope="row">@quote.Key</th>
                <td>@quote.Value.Price</td>
            </tr>
        }
    </tbody>
</table>

Project.MvcClient/Views/People/Create.cshtml
@model Project.MvcClient.ViewModels.PeopleViewModels.CreatePersonRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>CreatePersonRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Project.MvcClient/Views/People/Delete.cshtml
@model Project.MvcClient.ViewModels.PeopleViewModels.PersonItem

@{
    ViewData["Title"] = "DeleteAsync";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DeleteAsync</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-id="@Model.Id">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Project.MvcClient/Views/People/Details.cshtml
@model Project.MvcClient.ViewModels.PeopleViewModels.PersonItem

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>PersonItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Project.MvcClient/Views/People/Edit.cshtml
@model Project.MvcClient.ViewModels.PeopleViewModels.UpdatePerson

@{
    ViewData["Title"] = "UpdateAsync";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UpdateAsync</h1>

<h4>UpdatePerson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Project.MvcClient/Views/People/Index.cshtml
@model List<PersonItem>;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>People</h1>
<a asp-action="Create" class="btn btn-primary">Create new Person</a>
<br />
<br />
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(PersonItem person in Model)
        {
            <tr>
                <th scope="row">@person.Id</th>
                <td>@person.FirstName</td>
                <td>@person.LastName</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@person.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@person.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@person.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<hr/>

Project.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project.MvcClient</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.MvcClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project.MvcClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CryptoCurrencies" asp-action="Index">Bitcoin Rate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Project.MvcClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>